services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - '3000:3000'

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4200:80'
    depends_on:
      - backend

volumes:
  pgdata:
